#ifndef VELLEZ_ESP8266_DEF_LIMITS_H
#define VELLEZ_ESP8266_DEF_LIMITS_H

#define LIMIT_DFPLAYER_MAX_TRACK_NUM 2999
#define LIMIT_DFPLAYER_MAX_VOLUME 30
#define LIMIT_SETTINGS_MAX_STRING_LENGTH 31

#endif // VELLEZ_ESP8266_DEF_LIMITS_H
